databases:
 - name: joynotes
   region: frankfurt
   databaseName: joynotes_db
   user: joynotes_backend

services:
 - type: web
   name: joynotes-backend
   region: frankfurt
   branch: master
   healthCheckPath: /health
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn joynotes.wsgi:application"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: joynotes
         property: connectionString
     - key: SECRET_KEY
       generateValue: true
     - key: WEB_CONCURRENCY
       value: 1
     - key: ENVIRONMENT
       value: production