databases:
 - name: foink
   region: frankfurt
   databaseName: foink_db
   user: foink_backend

services:
 - type: web
   name: foink-backend
   region: frankfurt
   branch: master
   healthCheckPath: /health
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn joynotes.wsgi:application"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: foink
         property: connectionString
     - key: SECRET_KEY
       generateValue: true
     - key: WEB_CONCURRENCY
       value: 1
     - key: ENVIRONMENT
       value: production