# Generated by Django 3.0.8 on 2020-11-17 20:55

import accounts.utils
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(default=accounts.utils.generate_uuid, max_length=255, unique=True)),
                ('name', models.CharField(max_length=2048)),
                ('email', models.CharField(max_length=2048, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
