# Generated by Django 3.0.8 on 2020-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='category',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
