# Generated by Django 3.0.8 on 2020-11-17 22:05
import csv
import os

from django.db import migrations


def ingest_authorities(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Authority = apps.get_model('authorities', 'Authority')
    CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
    DATA_DIR = CURRENT_DIR + '/data/'

    for (path, _, filenames) in os.walk(DATA_DIR):
        authorities = []
        for filename in filenames:
            filepath = path + filename
            with open(filepath) as open_csv:
                reader = csv.reader(open_csv)
                for row in reader:
                    name = row[0]
                    category = row[1]
                    email = row[2]
                    authorities.append(Authority(
                        name=name,
                        category=category,
                        email=email,
                    ))
        Authority.objects.bulk_create(authorities)



class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0002_authority_category'),
    ]

    operations = [
        migrations.RunPython(ingest_authorities),
    ]
