# Generated by Django 3.0.8 on 2020-11-18 12:27

from django.db import migrations
from django.db.models import Count


def dedupe_authorities(apps, schema_editor):
    Authority = apps.get_model('authorities', 'Authority')
    dupes = Authority.objects.values(
        'name'
    ).annotate(
        Count('id')
    ) .order_by().filter(
        id__count__gt=1
    )
    for dupe in dupes:
        qs = Authority.objects.filter(name=dupe['name'])
        emails = qs.values_list('email', flat=True)
        if len(set(emails)) == 1:
            to_delete = qs.last()
            to_delete.delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_auto_20201117_2205'),
    ]

    operations = [
        migrations.RunPython(dedupe_authorities, backwards),
    ]
